// ================================================================
// js/auth.js
// Vendor authentication helpers (localStorage Demo Mode)
// Uses localStorage so credentials persist across tabs/windows
// ================================================================

export function getCurrentVendorId() {
  const val = localStorage.getItem('vendor_id');
  if (!val || val === 'null' || val === 'undefined') return null;
  return val;
}

export function getCurrentVendorName() {
  const val = localStorage.getItem('vendor_name');
  if (!val || val === 'null' || val === 'undefined') return 'Vendor';
  return val;
}

export function requireVendorAuth() {
  const id = getCurrentVendorId();
  if (!id) return null;
  return {
    id,
    phone: '+971501234567',
    user_metadata: { company_name: getCurrentVendorName() }
  };
}

// Ensure alias exists for requireAuth
export const requireAuth = requireVendorAuth;

// Keep getCurrentUser backwards compatible
export async function getCurrentUser() {
  const vendorId = getCurrentVendorId();
  if (!vendorId) return null;
  return {
    id: vendorId,
    phone: '+971501234567',
    user_metadata: { company_name: getCurrentVendorName() }
  };
}

// Keep getVendorId backwards compatible
export async function getVendorId() {
  return getCurrentVendorId();
}

export function logout() {
  localStorage.removeItem('vendor_id');
  localStorage.removeItem('vendor_name');
  window.location.href = '/demo.html';
}

// ── UTILITIES ────────────────────────────────────────────────────
export function formatUAEPhone(input) {
  const digits = input.replace(/\D/g, '');
  if (digits.startsWith('971')) return `+${digits}`;
  if (digits.startsWith('0')) return `+971${digits.slice(1)}`;
  return `+971${digits}`;
}

export function validateTRN(trn) {
  return /^\d{15}$/.test(trn.replace(/\s/g, ''));
}

export function generateDriverToken(jobId, driverId, vendorId) {
  // Demo mode: return a simple token
  return `demo-${jobId}-${driverId}`;
}

// Used by js/driver.js (driver.html currently has its own inline demo validator).
export async function validateDriverToken(jobCode, token) {
  // MVP demo validation:
  // - accept the literal 'demo-token' used by driver-login.html
  // - accept tokens generated by generateDriverToken()
  if (token === 'demo-token') return { valid: true };
  if (typeof token === 'string' && token.startsWith(`demo-${jobCode}-`)) return { valid: true };
  if (typeof token === 'string' && token.startsWith('demo-')) return { valid: true };
  return { valid: false };
}
