// ================================================================
// js/pdf.js
// All PDF generation logic using jsPDF.
// Loads jsPDF from CDN — no npm install needed.
// All functions return a Blob URL and upload to Supabase Storage.
// ================================================================

// jsPDF is loaded via <script> tag in each HTML page that needs it:
// <script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js"></script>

import { uploadDocument } from './supabase.js';
import { formatAED } from './whatsapp.js';

// ── BRANDING ─────────────────────────────────────────────────────
const BRAND = {
  name: 'Kasper Vendor OS',
  color: [245, 158, 11],    // Gold — RGB
  dark:  [13, 27, 42],      // Navy
  teal:  [0, 212, 200],
  gray:  [120, 139, 160],
  light: [245, 245, 245],
};

// ── SHARED HEADER ────────────────────────────────────────────────

function addHeader(doc, vendor, docTitle, docRef) {
  const pageW = doc.internal.pageSize.getWidth();

  // Dark header bar
  doc.setFillColor(...BRAND.dark);
  doc.rect(0, 0, pageW, 28, 'F');

  // Kasper branding (left)
  doc.setFontSize(8);
  doc.setTextColor(...BRAND.color);
  doc.setFont('helvetica', 'bold');
  doc.text('⬡ KASPER', 14, 10);
  doc.setFontSize(7);
  doc.setTextColor(150, 170, 180);
  doc.setFont('helvetica', 'normal');
  doc.text('VENDOR OS', 14, 15);

  // Document title (center)
  doc.setFontSize(11);
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.text(docTitle, pageW / 2, 12, { align: 'center' });
  doc.setFontSize(7);
  doc.setTextColor(150, 170, 180);
  doc.setFont('helvetica', 'normal');
  doc.text(docRef, pageW / 2, 18, { align: 'center' });

  // Vendor name (right)
  doc.setFontSize(8);
  doc.setTextColor(200, 210, 220);
  doc.setFont('helvetica', 'bold');
  doc.text(vendor.company_name || '', pageW - 14, 10, { align: 'right' });
  doc.setFontSize(7);
  doc.setFont('helvetica', 'normal');
  doc.text(`TRN: ${vendor.trn || '—'}`, pageW - 14, 15, { align: 'right' });

  // Reset
  doc.setTextColor(0, 0, 0);
}

function addFooter(doc, pageNum) {
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();

  doc.setFillColor(...BRAND.light);
  doc.rect(0, pageH - 14, pageW, 14, 'F');

  doc.setFontSize(7);
  doc.setTextColor(...BRAND.gray);
  doc.setFont('helvetica', 'normal');
  doc.text('Generated by Kasper Vendor OS · kasperlogistics.vercel.app', 14, pageH - 5);
  doc.text(`Page ${pageNum}`, pageW - 14, pageH - 5, { align: 'right' });
  doc.setTextColor(0, 0, 0);
}

function section(doc, y, title) {
  doc.setFillColor(...BRAND.color);
  doc.rect(14, y, 4, 6, 'F');
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...BRAND.dark);
  doc.text(title, 21, y + 4.5);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(0, 0, 0);
  return y + 10;
}

function infoTable(doc, y, rows, col1W = 50, rowH = 7) {
  const pageW = doc.internal.pageSize.getWidth();
  const col2X = 14 + col1W;
  const col2W = pageW - 14 - col1W - 14;

  rows.forEach(([label, value], i) => {
    const bg = i % 2 === 0 ? [250, 250, 250] : [255, 255, 255];
    doc.setFillColor(...bg);
    doc.rect(14, y, col1W, rowH, 'F');
    doc.rect(col2X, y, col2W, rowH, 'F');

    doc.setDrawColor(220, 220, 220);
    doc.rect(14, y, col1W + col2W, rowH, 'S');

    doc.setFontSize(8);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...BRAND.gray);
    doc.text(label, 17, y + rowH - 2);

    doc.setFont('helvetica', 'normal');
    doc.setTextColor(30, 30, 30);
    doc.text(String(value || '—'), col2X + 3, y + rowH - 2);

    y += rowH;
  });

  return y + 4;
}

function vatTable(doc, y, priceExVAT, vatAmount, totalIncVAT) {
  const pageW = doc.internal.pageSize.getWidth();
  const rightX = pageW - 14;

  const rows = [
    ['Amount (ex-VAT)', `AED ${formatAED(priceExVAT)}`],
    ['VAT (5%)', `AED ${formatAED(vatAmount)}`],
  ];

  doc.setFontSize(8);
  let ry = y;
  rows.forEach(([l, v]) => {
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...BRAND.gray);
    doc.text(l, rightX - 60, ry, { align: 'right' });
    doc.setTextColor(30, 30, 30);
    doc.text(v, rightX, ry, { align: 'right' });
    ry += 6;
  });

  // Total box
  ry += 2;
  doc.setFillColor(...BRAND.dark);
  doc.rect(rightX - 80, ry - 5, 80, 9, 'F');
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...BRAND.color);
  doc.text('TOTAL (inc-VAT)', rightX - 60, ry + 1, { align: 'right' });
  doc.setTextColor(255, 255, 255);
  doc.text(`AED ${formatAED(totalIncVAT)}`, rightX - 2, ry + 1, { align: 'right' });
  doc.setTextColor(0, 0, 0);

  return ry + 14;
}

// ================================================================
// 1. QUOTE PDF
// ================================================================

export async function generateQuotePDF(job, vendor) {
  const { jsPDF } = window.jspdf;
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const pageW = doc.internal.pageSize.getWidth();
  const now = new Date();
  const validUntil = new Date(now.getTime() + 48 * 60 * 60 * 1000);

  addHeader(doc, vendor, 'QUOTATION', `QUO-${job.job_code}`);

  let y = 34;

  // Alert bar
  doc.setFillColor(255, 248, 225);
  doc.rect(14, y, pageW - 28, 8, 'F');
  doc.setFontSize(7.5);
  doc.setTextColor(...BRAND.color);
  doc.setFont('helvetica', 'bold');
  doc.text(`⏱ This quote is valid for 48 hours — until ${validUntil.toLocaleDateString('en-AE', { day:'2-digit', month:'short', year:'numeric', hour:'2-digit', minute:'2-digit' })}`, pageW / 2, y + 5.5, { align: 'center' });
  doc.setTextColor(0, 0, 0);
  y += 13;

  y = section(doc, y, 'JOB DETAILS');
  y = infoTable(doc, y, [
    ['Reference', job.job_code],
    ['Service type', job.service_type?.charAt(0).toUpperCase() + job.service_type?.slice(1)],
    ['Origin', job.origin],
    ['Destination', job.destination],
    ['Pickup date', job.pickup_date],
    ['Cargo / Equipment', job.cargo_type || job.equipment_type],
    ['Special requirements', job.special_requirements || 'None'],
    ['Quote date', now.toLocaleDateString('en-AE', { day:'2-digit', month:'short', year:'numeric' })],
  ]);

  y += 4;
  y = section(doc, y, 'PRICING');

  const priceExVAT = job.quoted_price / 1.05;
  const vatAmount  = job.quoted_price - priceExVAT;
  y = vatTable(doc, y, priceExVAT, vatAmount, job.quoted_price);

  y += 4;
  y = section(doc, y, 'VENDOR DETAILS');
  y = infoTable(doc, y, [
    ['Company', vendor.company_name],
    ['TRN', vendor.trn || '—'],
    ['Bank', vendor.bank_name || '—'],
    ['IBAN', vendor.bank_iban || '—'],
    ['Payment terms', 'Net 30 days from invoice date'],
  ]);

  // Approve / Decline buttons (text links)
  y += 8;
  doc.setFillColor(...BRAND.teal);
  doc.rect(14, y, (pageW - 32) / 2, 10, 'F');
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...BRAND.dark);
  doc.text('✓ APPROVE QUOTE', 14 + (pageW - 32) / 4, y + 6.5, { align: 'center' });

  doc.setFillColor(240, 240, 240);
  doc.rect(14 + (pageW - 32) / 2 + 4, y, (pageW - 32) / 2, 10, 'F');
  doc.setTextColor(...BRAND.gray);
  doc.text('✗ DECLINE', 14 + (pageW - 32) / 2 + 4 + (pageW - 32) / 4, y + 6.5, { align: 'center' });

  doc.setTextColor(0, 0, 0);

  addFooter(doc, 1);

  return uploadPDF(doc, vendor.id, job.job_code, 'quote.pdf', 'quote_pdf_url', job.job_code);
}

// ================================================================
// 2. PURCHASE ORDER PDF
// ================================================================

export async function generatePOPDF(job, vendor) {
  const { jsPDF } = window.jspdf;
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const pageW = doc.internal.pageSize.getWidth();
  const now = new Date();

  addHeader(doc, vendor, 'PURCHASE ORDER', `PO-${job.job_code}`);

  let y = 34;

  // PO header banner
  doc.setFillColor(...BRAND.dark);
  doc.rect(14, y, pageW - 28, 12, 'F');
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(255, 255, 255);
  doc.text('OFFICIAL PURCHASE ORDER', pageW / 2, y + 8, { align: 'center' });
  doc.setTextColor(0, 0, 0);
  y += 17;

  y = section(doc, y, 'JOB DETAILS');
  y = infoTable(doc, y, [
    ['PO Number', `PO-${job.job_code}`],
    ['Job Reference', job.job_code],
    ['Service type', job.service_type],
    ['Origin', job.origin],
    ['Destination', job.destination],
    ['Pickup date', job.pickup_date],
    ['Cargo / Equipment', job.cargo_type || job.equipment_type],
    ['Client company', job.client_company],
    ['PO date', now.toLocaleDateString('en-AE')],
  ]);

  y += 4;
  y = section(doc, y, 'PRICING');

  const priceExVAT = job.quoted_price / 1.05;
  const vatAmount  = job.quoted_price - priceExVAT;
  y = vatTable(doc, y, priceExVAT, vatAmount, job.quoted_price);

  y += 4;
  y = section(doc, y, 'PAYMENT DETAILS');
  y = infoTable(doc, y, [
    ['Payment terms', 'Net 30 days from delivery date'],
    ['Bank name', vendor.bank_name || '—'],
    ['IBAN', vendor.bank_iban || '—'],
    ['Reference', `PO-${job.job_code}`],
  ]);

  // Signature box
  y += 6;
  doc.setDrawColor(200, 200, 200);
  doc.rect(14, y, (pageW - 32) / 2, 20, 'S');
  doc.setFontSize(7);
  doc.setTextColor(...BRAND.gray);
  doc.text('Authorised by (Kasper)', 17, y + 6);
  doc.text('Date: _______________', 17, y + 16);

  doc.rect(14 + (pageW - 32) / 2 + 4, y, (pageW - 32) / 2, 20, 'S');
  doc.text('Accepted by (Vendor)', 14 + (pageW - 32) / 2 + 7, y + 6);
  doc.text('Date: _______________', 14 + (pageW - 32) / 2 + 7, y + 16);
  doc.setTextColor(0, 0, 0);

  addFooter(doc, 1);

  return uploadPDF(doc, vendor.id, job.job_code, 'po.pdf', 'po_pdf_url', job.job_code);
}

// ================================================================
// 3. INVOICE PDF
// ================================================================

export async function generateInvoicePDF(job, vendor, telrPaymentUrl) {
  const { jsPDF } = window.jspdf;
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const pageW = doc.internal.pageSize.getWidth();
  const now = new Date();
  const dueDate = new Date(now.getTime() + 30 * 24 * 60 * 60 * 1000);

  addHeader(doc, vendor, 'TAX INVOICE', `INV-${job.job_code}`);

  let y = 34;

  // UAE FTA required banner
  doc.setFillColor(232, 245, 233);
  doc.rect(14, y, pageW - 28, 7, 'F');
  doc.setFontSize(7);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(27, 94, 32);
  doc.text('UAE VAT COMPLIANT TAX INVOICE — Federal Tax Authority Registered', pageW / 2, y + 5, { align: 'center' });
  doc.setTextColor(0, 0, 0);
  y += 12;

  y = section(doc, y, 'INVOICE DETAILS');
  y = infoTable(doc, y, [
    ['Invoice number', `INV-${job.job_code}`],
    ['PO reference', `PO-${job.job_code}`],
    ['Job reference', job.job_code],
    ['Invoice date', now.toLocaleDateString('en-AE')],
    ['Due date', dueDate.toLocaleDateString('en-AE')],
    ['Tax period', `${now.toLocaleDateString('en-AE', { month:'long', year:'numeric' })}`],
  ]);

  y += 4;
  y = section(doc, y, 'BILL TO');
  y = infoTable(doc, y, [
    ['Company', job.client_company],
    ['Contact', job.client_name],
    ['Phone', job.client_phone],
    ['Email', job.client_email || '—'],
  ]);

  y += 4;
  y = section(doc, y, 'SERVICES RENDERED');
  y = infoTable(doc, y, [
    ['Service', `${job.service_type} — ${job.origin} to ${job.destination}`],
    ['Date', job.pickup_date],
    ['Driver', job.driver_name],
    ['Vehicle', job.vehicle_plate],
    ['Cargo', job.cargo_type || job.equipment_type],
    ['Delivery reference', job.epod_pdf_url ? `ePOD-${job.job_code}` : 'Pending'],
  ]);

  y += 4;
  y = section(doc, y, 'AMOUNT DUE');
  const priceExVAT = job.quoted_price / 1.05;
  const vatAmount  = job.quoted_price - priceExVAT;
  y = vatTable(doc, y, priceExVAT, vatAmount, job.quoted_price);

  // Payment link
  if (telrPaymentUrl) {
    y += 4;
    doc.setFillColor(225, 245, 254);
    doc.rect(14, y, pageW - 28, 10, 'F');
    doc.setFontSize(8);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(21, 101, 192);
    doc.text('💳 Pay online: ', 17, y + 6.5);
    doc.setFont('helvetica', 'normal');
    doc.text(telrPaymentUrl, 42, y + 6.5);
    doc.setTextColor(0, 0, 0);
    y += 15;
  }

  // Bank transfer alternative
  y = section(doc, y, 'BANK TRANSFER DETAILS');
  y = infoTable(doc, y, [
    ['Bank', vendor.bank_name || '—'],
    ['IBAN', vendor.bank_iban || '—'],
    ['Reference', `INV-${job.job_code}`],
    ['Vendor TRN', vendor.trn || '—'],
  ]);

  addFooter(doc, 1);

  return uploadPDF(doc, vendor.id, job.job_code, 'invoice.pdf', 'invoice_pdf_url', job.job_code);
}

// ================================================================
// 4. ePOD PDF
// ================================================================

export async function generateEPODPDF(job, vendor, { driverSigB64, clientSigB64, photoUrl, driverGPS }) {
  const { jsPDF } = window.jspdf;
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const pageW = doc.internal.pageSize.getWidth();

  addHeader(doc, vendor, 'PROOF OF DELIVERY', `ePOD-${job.job_code}`);

  let y = 34;

  // Confirmed banner
  doc.setFillColor(232, 245, 233);
  doc.rect(14, y, pageW - 28, 8, 'F');
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(27, 94, 32);
  doc.text('✓ DELIVERY CONFIRMED — BOTH PARTIES SIGNED', pageW / 2, y + 5.5, { align: 'center' });
  doc.setTextColor(0, 0, 0);
  y += 13;

  y = section(doc, y, 'DELIVERY DETAILS');
  y = infoTable(doc, y, [
    ['Job reference', job.job_code],
    ['Origin', job.origin],
    ['Destination', job.destination],
    ['Cargo', job.cargo_type || job.equipment_type],
    ['Driver', job.driver_name],
    ['Vehicle plate', job.vehicle_plate],
    ['Delivery time', job.epod_driver_at ? new Date(job.epod_driver_at).toLocaleString('en-AE') : '—'],
    ['GPS at delivery', driverGPS ? `${driverGPS.lat?.toFixed(5)}, ${driverGPS.lng?.toFixed(5)}` : '—'],
  ]);

  // Signatures
  y += 4;
  y = section(doc, y, 'SIGNATURES');

  const halfW = (pageW - 32) / 2;

  // Driver signature box
  doc.setDrawColor(200, 200, 200);
  doc.rect(14, y, halfW, 32, 'S');
  doc.setFontSize(7);
  doc.setTextColor(...BRAND.gray);
  doc.text('DRIVER SIGNATURE', 17, y + 5);
  doc.text(job.driver_name || '', 17, y + 10);

  if (driverSigB64) {
    try {
      doc.addImage(driverSigB64, 'PNG', 16, y + 12, halfW - 4, 16);
    } catch (e) { /* sig not renderable */ }
  }

  doc.setTextColor(0, 0, 0);
  doc.setFontSize(7);
  doc.text(job.epod_driver_at ? new Date(job.epod_driver_at).toLocaleString('en-AE') : '', 17, y + 29);

  // Client signature box
  doc.rect(14 + halfW + 4, y, halfW, 32, 'S');
  doc.setTextColor(...BRAND.gray);
  doc.text('CLIENT SIGNATURE', 14 + halfW + 7, y + 5);
  doc.text(job.client_name || '', 14 + halfW + 7, y + 10);

  if (clientSigB64) {
    try {
      doc.addImage(clientSigB64, 'PNG', 14 + halfW + 6, y + 12, halfW - 4, 16);
    } catch (e) { /* sig not renderable */ }
  }

  doc.setTextColor(0, 0, 0);
  doc.text(job.epod_client_at ? new Date(job.epod_client_at).toLocaleString('en-AE') : '', 14 + halfW + 7, y + 29);
  y += 36;

  // Delivery photo
  if (photoUrl) {
    y += 4;
    y = section(doc, y, 'DELIVERY PHOTO');
    doc.setFontSize(7);
    doc.setTextColor(...BRAND.gray);
    doc.text(`Photo: ${photoUrl}`, 14, y);
    // Note: embedding remote images in jsPDF requires fetching and converting to base64
    // For MVP, we show the URL. Implement image embedding in Phase 2.
    y += 8;
  }

  addFooter(doc, 1);

  return uploadPDF(doc, vendor.id, job.job_code, 'epod.pdf', 'epod_pdf_url', job.job_code);
}

// ── UPLOAD HELPER ─────────────────────────────────────────────────

async function uploadPDF(doc, vendorId, jobCode, filename, urlField, _jobCode) {
  const blob = doc.output('blob');
  const url = await uploadDocument(vendorId, jobCode, filename, blob);
  return { url, blob, dataUrl: doc.output('datauristring') };
}
